= Install Anypoint Monitoring On-Premise

You can install Anypoint Monitoring on an on-premises server to monitor applications running on that server. On premises monitoring for hybrid deployments must be enabled at the master org level.

== Before You Begin

Open port 443 in your outbound firewall, if you have one. The Anypoint Monitoring agent sends monitoring data to the Anypoint Monitoring cloud endpoint. Anypoint Monitoring data is transferred using the Lumberjack protocol, an open-source protocol for transferring log data over a highly-efficient bidirectional binary channel.

== Supported Operating Systems

Ensure that Anypoint Monitoring will be installed on a server running one of the following operating systems:

* CentOS 7
* RedHat Enterprise Linux 7.0
* Ubuntu 14.04 and 15.04
* Windows Server 2008 R2 or later

== Supported Versions of Mule Runtime

Ensure that one of the versions of Mule Runtime that is listed below is running on the server:

* 4.1.x
* 3.9.1
* 3.9.0
* 3.8.7

== Hardware Prerequisites

Ensure that the server has at least the minimum hardware requirements for Anypoint Monitoring:

* 2GHz CPU or 1 virtual CPU
* 1GB RAM
* 4GB disk space

== Install Anypoint Monitoring

Instructions for downloading and installing Anypoint Monitoring for an on-premises installation are located in the *Settings* section of the Anypoint Monitoring user interface.

[NOTE]
You must set the *Environment* and *Server* properties before you download the `am.zip`.

== Access Settings

To see the *Settings* tab, you must:

* Have the Anypoint Monitoring User permission. See xref:access-management::users#granting-permissions-and-roles-to-users[Granting Permissions and Roles to Users].
* Have on premises monitoring for hybrid deployments enabled at your master org level. Check with your account representative to verify this.


. Sign into Anypoint Platform and navigate to *Anypoint Monitoring*.
. In the menu on the left, click *Settings*. +
The instructions for installing Anypoint Monitoring on premises are displayed. You can also download the Anypoint Monitoring installation ZIP file from this page, but make sure you set the *Environment* and *Server* properties before you download the file.


== Verify that Anypoint Monitoring is Running

1. Wait 10 minutes for the configuration to propagate.
1. Go to http://anypoint.mulesoft.com and sign in.
1. Navigate to *Anypoint Monitoring*.
1. On the *Built-in Dashboards* page, select an app that is deployed on the server where you installed Anypoint Monitoring.
1. Check whether the CPU Utilization and Memory Utilization charts are displaying data.

*Result:* If you see data in the charts, Anypoint Monitoring is installed and running.

If you do not see data in the charts, check whether Anypoint Monitoring is unable to connect to the endpoint.

[NOTE]
You can whitelist the endpoint for outbound firewall rules so your server will allow connections, if necessary. The endpoint is displayed in the gray box in Step 5 on the page, under the OS.

11. Log into the server on which Anypoint Monitoring is running.
11. Open the log file for the data-transfer agent. The log file is in this path: `./am/log/filebeat`
11. Look for entries that mention connection failures or connection retries.

*What to do next:*

- If you find any such entries, ensure that port 443 in your outbound firewall is open.
- If you do not find any such entries, contact technical support.

== See Also

* xref:4.1@mule-runtime::runtime-installation-task.adoc[To Download and Install the Mule Runtime 4 EE Standalone]
* xref:3.9@mule-runtime::installing.adoc[Installing and Deploying Mule Runtime 3.9]
* xref:3.8@mule-runtime::installing.adoc[Installing and Deploying Mule Runtime 3.8]
