= Install Anypoint Monitoring On-Premises

You can install Anypoint Monitoring on an on-premises server if you want to monitor applications that are running on that server.

== Before you begin

Open port 443 in your outbound firewall, if you have one. The Anypoint Monitoring agent sends monitoring data to the Anypoint Monitoring cloud endpoint. Anypoint Monitoring data is transferred using the Lumberjack protocol, an open source protocol for transferring log data over a highly-efficient bidirectional binary channel.

== Supported operating systems

Ensure that the server that you are planning to install Anypoint Monitoring on is running one of the following operating systems:

* CentOS 7
* RedHat Enterprise Linux 7.0
* Ubuntu 14.04 and 15.04

== Supported versions of Mule Runtime

Ensure that one of the versions of Mule Runtime that is listed below is running on the server:

* 4.1.2
* 4.1.1
* 3.9.1
* 3.9.0
* 3.8.7

== Hardware prerequisites

* 2GHz CPU or 1 virtual CPU
* 1GB RAM
* 4GB disk space

== Installing Anypoint Monitoring

Instructions for downloading and installing Anypoint Monitoring for an on-premises installation are located in the *Settings* section of the Anypoint Monitoring user interface.

== Confirming that Anypoint Monitoring is running

1. Wait 10 minutes for configuration to propagate
1. Go to anypoint.mulesoft.com <http://anypoint.mulesoft.com> and log in.
1. Navigate to Anypoint Monitoring.
1. On the *Built-in Dashboards* page, select an application that is deployed on the server where you installed Anypoint Monitoring.
1. Check whether the CPU Utilization and Memory Utilization charts are displaying data.

*Result:* If you see data in the charts, Anypoint Monitoring is installed and running.

If you do not see data in the charts, check whether Anypoint Monitoring is unable to connect to the endpoint.

11. Log into the server on which Anypoint Monitoring is running.
11. Open the log file for the data-transfer agent. The log file is in this path: `/var/log/filebeat`
11. Look for entries that mention connection failures or connection retries.

*What to do next:*

- If you find any such entries, ensure that port 443 in your outbound firewall is open.
- If you do not find any such entries, contact technical support.

== See Also

* xref:4.1@mule-runtime::runtime-installation-task.adoc[To Download and Install the Mule Runtime 4 EE Standalone
]
* xref:3.9@mule-runtime::installing.adoc[Installing and Deploying Mule Runtime 3.9
]
* xref:3.8@mule-runtime::installing.adoc[Installing and Deploying Mule Runtime 3.8
]
