= Install Anypoint Monitoring On-Premise

You can install Anypoint Monitoring on an on-premises server to monitor applications running on that server. On premises monitoring for hybrid deployments must be enabled at the master org level.

== Before You Begin

Open ports 443 and 5044 in your outbound firewall, if you have one. The Anypoint Monitoring agent sends monitoring data to the Anypoint Monitoring cloud endpoint. Anypoint Monitoring data is transferred using the Lumberjack protocol, an open-source protocol for transferring log data over a highly-efficient bidirectional binary channel. Data is securely transmitted using mutual TLS encryption. 

Outbound connections are made to the following endpoints:

* US Control Plane
** arm-auth-proxy.prod.cloudhub.io:443
** dias-ingestor-nginx.prod.cloudhub.io:5044
* EU Control Plane
** arm-auth-proxy.prod-eu.msap:443
** dias-ingestor-nginx.prod-eu.msap.io:5044

== Supported Operating Systems

Ensure that Anypoint Monitoring is installed on a server running one of the following operating systems:

* CentOS 7
* RedHat Enterprise Linux 7.0
* Ubuntu 14.04 and 15.04
* Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2, Windows Server 2016, Windows Server 2019

== Supported Versions of Mule Runtime Engine

Ensure that one of the following Mule runtime engine versions is running on the server:

* 4.1.4
* 4.1.3
* 4.1.2
* 4.1.1
* 3.9.1
* 3.9.0
* 3.8.7

== Supported Versions of Mule Runtime Manager Agent

Ensure that one of the following Mule Runtime Manager agent versions is installed in the Mule runtime engine running on the server:

* Runtime Manager Agent 2.1.7
* Runtime Manager Agent 2.1.6
* Runtime Manager Agent 1.11.3
* Runtime Manager Agent 1.11.2
* Runtime Manager Agent 1.11.1
* Runtime Manager Agent 1.11.0
* Runtime Manager Agent 1.10.0

== Hardware Prerequisites

Ensure that the server has at least the minimum hardware requirements for Anypoint Monitoring:

* 2GHz CPU or 1 virtual CPU
* 1GB RAM
* 4GB disk space

== Install Anypoint Monitoring

Instructions for downloading and installing Anypoint Monitoring for an on-premises installation are located in the *Settings* section of the Anypoint Monitoring user interface.

[NOTE]
You must set the *Environment* and *Server* properties before you download the `am.zip`.

== Access Settings

To see the *Settings* tab, you must:

* Have the Anypoint Monitoring User permission. See xref:access-management::users#granting-permissions-and-roles-to-users[Granting Permissions and Roles to Users].
* Have on premises monitoring for hybrid deployments enabled at your master org level. Check with your account representative to verify this.


. Sign into Anypoint Platform and navigate to *Anypoint Monitoring*.
. In the menu on the left, click *Settings*. +
The instructions for installing Anypoint Monitoring on premises are displayed. You can also download the Anypoint Monitoring installation ZIP file from this page. +
[NOTE] Make sure you set the *Environment* and *Server* properties before you download the file.

== Verify that Anypoint Monitoring is Running

1. Wait 10 minutes for the configuration to propagate.
1. Go to http://anypoint.mulesoft.com and sign in.
1. Navigate to *Anypoint Monitoring*.
1. On the *Built-in Dashboards* page, select an app that is deployed on the server where you installed Anypoint Monitoring.
1. Check whether the CPU Utilization and Memory Utilization charts are displaying data.

If you see data in the charts, Anypoint Monitoring is installed and running.

If you do not see data in the charts, verify that Anypoint Monitoring is able to connect to the endpoint.

[NOTE]
If necessary, you can whitelist the endpoint for outbound firewall rules so your server allows connections. The endpoint is displayed in the gray box in Step 5 on the page, under the OS.

11. Log into the server on which Anypoint Monitoring is running.
11. Open the log file for the data-transfer agent. The log file is in this path: `./am/log/filebeat`
11. Look for entries that mention connection failures or connection retries.

=== What to do Next

- If you find connection failure or retry entries, ensure that ports 443 and 5044 in your outbound firewall are open.
- If you do not find connection failure or retry entries, contact MuleSoft technical support.

== See Also

* xref:4.1@mule-runtime::runtime-installation-task.adoc[To Download and Install the Mule Runtime 4 EE Standalone]
* xref:runtime-manager::installing-and-configuring-runtime-manager-agent.adoc[Installing and Configuring Mule Runtime Manager Agent]
* xref:3.9@mule-runtime::installing.adoc[Installing and Deploying Mule Runtime 3.9]
* xref:3.8@mule-runtime::installing.adoc[Installing and Deploying Mule Runtime 3.8]
