= Install Anypoint Monitoring On-Premises

You can install Anypoint Monitoring on an on-premises server to monitor applications running on that server. 

The install script prompts for whether Anypoint Monitoring should be installed as a service. If you don't want to have it preset as a service by the installer, select `no`. You can also call the install script with the `-x` argument to skip this prompt. If you skip the prompt Anypoint Monitoring is not installed as a service. 

== Before You Begin

If you have an outbound firewall, open ports 443 and 5044. The Anypoint Monitoring agent sends monitoring data to the Anypoint Monitoring cloud endpoint. Anypoint Monitoring data is transferred using an open-source protocol for transferring log data over a highly-efficient bidirectional binary channel. Data is securely transmitted using mutual TLS encryption. 

Outbound connections are made to the following endpoints:

* US Control Plane
** arm-auth-proxy.prod.cloudhub.io:443
** dias-ingestor-nginx.prod.cloudhub.io:5044
* EU Control Plane
** arm-auth-proxy.prod-eu.msap:443
** dias-ingestor-nginx.prod-eu.msap.io:5044

Verify that you have on-premises monitoring for hybrid deployments enabled at your master org level. Check with your account representative if you aren't sure.

== Supported Operating Systems

Ensure that Anypoint Monitoring is installed on a server running one of the following operating systems:

* CentOS 7
* RedHat Enterprise Linux 7.0 and 7.6
* Ubuntu 14.04 and 15.04
* Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2, Windows Server 2016, Windows Server 2019

== Supported Versions of Mule Runtime Engine

Ensure that one of the following Mule runtime engine versions is running on the server:

* 4.1.5
* 4.1.4
* 4.1.3
* 4.1.2
* 4.1.1
* 3.9.2
* 3.9.1
* 3.9.0
* 3.8.7

== Supported Versions of Mule Runtime Manager Agent

Ensure that one of the following Mule Runtime Manager agent versions is installed in the Mule runtime engine running on the server:

* Runtime Manager Agent 2.1.9
* Runtime Manager Agent 2.1.7
* Runtime Manager Agent 2.1.6
* Runtime Manager Agent 1.11.3
* Runtime Manager Agent 1.11.2
* Runtime Manager Agent 1.11.1
* Runtime Manager Agent 1.11.0
* Runtime Manager Agent 1.10.0

== Hardware Prerequisites

Ensure that the server has at least the minimum hardware requirements for Anypoint Monitoring:

* 2GHz CPU or 1 virtual CPU
* 1GB RAM
* 4GB disk space

[[install_ap_monitoring_onprem]]
== Install Anypoint Monitoring 

Instructions for downloading and installing Anypoint Monitoring on-premises are located on the xref:monitoring-settings-page.adoc[*Settings* page] of the Anypoint Monitoring user interface. You can also download the Anypoint Monitoring installation ZIP (`am.zip`) file from this page. 


== Verify that Anypoint Monitoring is Running

1. Wait 10 minutes for the configuration to propagate.
1. Go to http://anypoint.mulesoft.com and sign in.
1. Navigate to *Anypoint Monitoring*.
1. On the *Built-in Dashboards* page, select an app that is deployed on the server where you installed Anypoint Monitoring.
1. Check whether the CPU Utilization and Memory Utilization charts are displaying data. +
If you see data in the charts, Anypoint Monitoring is installed and running. +
If you do not see data in the charts, verify that Anypoint Monitoring is able to connect to the endpoint. +
[NOTE]
If necessary, you can whitelist the endpoint for outbound firewall rules so your server allows connections. The endpoint is displayed in the gray box in Step 5 on the page, under the OS.
11. Log into the server on which Anypoint Monitoring is running.
11. Open the log file for the data-transfer agent. The log file is in this path: `./am/log/filebeat`
11. Look for entries that mention connection failures or connection retries.

== Update the Monitoring Agent

. In the `am` folder, run the following command: +
`./bin/uninstall script`
. Delete the `am` folder.
. Follow the instructions for <<install_ap_monitoring_onprem,installing Anypoint Monitoring>> on-premises. 

=== What to do Next

- If you find connection failure or retry entries, ensure that ports 443 and 5044 in your outbound firewall are open.
- If you do not find connection failure or retry entries, contact MuleSoft technical support.

== See Also

* xref:monitoring-settings-page.adoc[Anypoint Monitoring Settings]
* xref:4.1@mule-runtime::runtime-installation-task.adoc[To Download and Install the Mule 4]
* xref:runtime-manager::installing-and-configuring-runtime-manager-agent.adoc[Installing and Configuring Mule Runtime Manager Agent]
* xref:3.9@mule-runtime::installing.adoc[Installing and Deploying Mule Runtime 3.9]
