= Manage Permissions for Anypoint Monitoring
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Monitoring has product-specific permissions that control access to its assets:

//all monitoring permissions
include::access-management::partial$include-permissions-monitoring.adoc[tag=permsMonitoringAll]

The content you can access when you have the Anypoint Monitoring Administrator and Anypoint Monitoring Viewer permissions depends on other asset-specific permissions.
To view or modify content related to specific apps and APIs, you also need the appropriate access permissions for those assets.
For example, a user who has the Anypoint Monitoring Viewer permission and wants to view Anypoint Monitoring data for an on-premises app also needs the Read Applications permission (from Runtime Manager) in the same environment that the app is deployed to.

At minimum, you need the following permissions to read data in Anypoint Monitoring:

* View API Alerts (API Manager) for Flex API content
* Read Applications (Runtime Manager) for on-premises app content
* Read Servers (Runtime Manager) for Flex Gateway content

== See Also

* xref:access-management::teams.adoc[Access Management Teams]
* xref:access-management::roles.adoc[Access Management Roles]
* xref:access-management::managing-permissions.adoc[Access Management Managing Permissions]
* xref:access-management::external-organization-access.adoc[Access Management External Organization Access]
* xref:api-manager::environment-permission-task.adoc[Permissions in API Manager]
* xref:cloudhub-2::ps-assign-permissions.adoc[Permissions in CloudHub 2.0]
