= Manage Permissions for Anypoint Monitoring
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Platform provides predefined permissions and roles that administrators can assign in the *Access Management* section of Anypoint Platform.
Anypoint Monitoring has two product-specific permissions to control access for different types of users.

== Anypoint Monitoring Permissions

To control access to dashboards, reports, and metrics, use the following permissions for Anypoint Monitoring:

* Anypoint Monitoring Administrator: +
View, create, modify, and delete all content in Anypoint Monitoring.
+
* Anypoint Monitoring Viewer: +
View content in Anypoint Monitoring. Users with this permission cannot modify any Anypoint Monitoring content.

== See Also

* xref:access-management::teams.adoc[Access Management Teams]
* xref:access-management::roles.adoc[Access Management Roles]
* xref:access-management::managing-permissions.adoc[Access Management Managing Permissions]
* xref:access-management::external-organization-access.adoc[Access Management External Organization Access]
