= Explore Entities with Anypoint Insights

Anypoint Monitoring collects metrics on Mule apps and API instances (_entities_) deployed to CloudHub or CloudHub 2.0. 

Use *Anypoint Insights* to:

* View aggregated performance and error data at a glance.
+
You can filter this data to focus insights on the performance specific groups of apps and APIs.
* Review key metrics about the health of individual entities.
+
Metrics include request, latency, error, and JVM data.
* Identify and troubleshoot issues.
* Get up to seven days of data, or narrow the date and time range.

include::partial$include-monitoring-metrics-collection.adoc[leveloffset=+1]

== Before You Begin

Before getting started, ensure that you have:

* An Anypoint Platform account that has the Monitoring Viewer permission and the permissions required for viewing apps and APIs.
* A supported version of Mule Runtime engine.

== Supported Versions of Mule Runtime Engine

include::partial$include-supported-mule-runtime-version.adoc[]

== Access the Anypoint Insights  Page

include::partial$include-nav-steps-no-permissions.adoc[]

include::partial$include-nav-entities.adoc[]

The *Anypoint Insights*  page appears, showing a summary of data for entities in the active business group and in the selected environment configured in your profile.

== Search for Entities

The search bar on the *Anypoint Insights*  page enables you to create search parameters to curate different assortments of entity data on the page and to visualize and monitor the health status of multiple entities in their business groups and environments. You can add and remove attributes such as status, errors, and environments to further refine your results. Adding different search parameters changes data in the summary, metric cards, and charts, which is refreshed each time you conduct a new search. 

//Each search filter requires three pieces of information: an attribute name (for example, `entity_type`), an operator (for example, `=` or `IN`) and a value. The auto-suggest feature is triggered by clicking inside the search box or by entering a space. When the attribute name, an operator, and a value are provided, the search component creates a filter that is visually represented as a data pill. You can edit a search filter by double-clicking on the appropriate data pill. After all modifications are completed, you can use the enter key to convert the text to a search pill again. You can click on the *X* icon on the pill to remove it.

//this is from tech review but I really don't think it is needed. 

By default, the *Anypoint Insights* page shows data for entities from the default environment configured in your user profile. You can adjust your profile to see data for entities in one or more of your environments for the active business group to which you are logged in. 

//You can choose a different business group using the org switcher in the Anypoint Navigation bar. EM- FIX THIS

//The search bar also offers quick filters, such as `Top 10 entities with highest error volume`, to show you common scenarios at a glance. You can also combine these with attributes and metrics to further specify the content that appears. 

Curate your search results for entity data by using the following attributes:

* Environment
* Entity Name
* Entity Type
* Entity ID
* Deployment Type
* Entity Response Status
* Request Counts
* Response Time

When you provide multiple filters, the resulting data matches all of them. For example, the query to fetch the entities data would include an `AND` operator to combine all of the search filters.

=== Apply Search Parameters

include::partial$include-nav-steps-no-permissions.adoc[]

include::partial$include-nav-entities.adoc[]

. In the search bar, enter an attribute, element, business group, or environment to use for filtering your data.
+
Note that `requests_counts` and `response_time` are measurements of their respective metrics. To create a search filter that uses these two attributes,  choose an aggregating function:

 *  `COUNT` is the only supported aggregating function that you can use with `request_counts.
 * `PERCENTILE` is the only aggregating function that you can use with `response_time`.

//=== Example of Applied Search Parameters

//tbd

== Filter Data by Using the Time Period Selector

Use the time period selector to display data points collected for the last given period of time (such as the last 15 or 30 minutes) or over a given date and time range. Use the drop-down in the calendar icon to select the time period to display in a graph. Your setting applies across all traces in the *Anypoint Insights* page, including the Entities List.

While in Beta, this feature is only accessible to Titanium or Advanced subscription customers and displays only seven days worth of data. 

// REMOVED THIS: Organizations with a Gold, Platinum, or Starter subscription can view up to 30 days of data. Organizations with a Titanium or Advanced subscription can view up to one year of data.

If you don't see data in any of the cards, charts, or tables, ensure that you have chosen the appropriate date-time range in the date picker.

== Understand Summary and Performance Trends for Entities

The *Anypoint Insights* page provides key metrics and health indicators as performance metrics cards and charts. By default, the charts show data for entities in your current business group and environment. When you modify your search settings, the data in the charts changes accordingly. 

The following performance metrics cards appear.
 
=== Performance Metrics

Total Entities::

Total number of entities that match your current search conditions in the selected date and time range.

Entities with Errors::

Count of entities that have an error that matches your current search conditions in the selected date and time range. 

Errors are dependent on the context of the entity. For API entities, an error is based on the HTTP status code (for example, `4xx` or `5xx`) and for application entities, an error is based on the response status (for example, `FAILED`)

Total Requests::

Total request volume for entities that match your current search conditions in the selected date and time range. 

Error Rate:: 

Error rate for entities that match your current search conditions in the selected date and time range. The error rate is calculated using the total number of entity errors divided by the total number of requests for those entities.


=== Performance Trends Charts

Entities with Slow Response Times:: 

Response time of the top entities that match your current search conditions in the selected date and time range. The top entities are calculated based on the percentile values of their response times (highest response time to lowest response time). The chart uses `P99` as the percentile index by default; however, you can select `P95`, `P90`, or `P75` to use as the percentile index.

Error Volume:: 

Total number of entities that match your current search conditions in the selected date and time range. 

Errors are dependent on the context of the entity. For API entities, an error is based on the HTTP status code (for example, `4xx` or `5xx`) and for application entities, an error is based on the response status (for example, `FAILED`)

Request Volume:: 

The total number of request to entities that match your current search conditions in the selected date and time range. 

=== Entities List

The list of entities that match your current search conditions in the selected date and time range. This list is rendered as a table with columnar key metrics. By default, the table is sorted by the value in the `Request Volume` (descending) field. 

The following columns appear in the table:

* *Entity Name*: Name of the entity.
* *Entity Type*: Type of the entity. The value in this column is either `API` or `Application`.
* *Request Volume*: Total number of requests to the entity.
* *P95 Latency*: P95 response time latency, calculated in milliseconds. 
* *Error Rate*: Percentage of requests to the entity that result in errors. 
* *Deployment Type*: Runtime environment in which the entity is deployed. 

[[automatic-interval]]
== How Data is Aggregated in Intervals

Anypoint Monitoring aggregates data in charts based on the selected time interval. The number of data points shown in a chart varies based on your selected time interval.

//Em told by Sathish to remove the following stuff 
//[[average-response-times-app]]
//== Charting Inactivity for Average Response Time

//include::partial$average-response-time.adoc[]

//[[endpoint-operation-metrics]]
//== How Endpoint and Operation Use Metrics Are Gathered

//Anypoint Monitoring collects top occurring endpoints or operations for each data collection interval. Endpoints or operations that are not top occurring are sorted into a group called *Other*.

//In each data collection interval, top occurring endpoints or operations vary. An endpoint or operation that is top occurring in one interval may not be top occurring in the next.

//In Anypoint Monitoring charts and tables, the data comes from multiple data collection intervals. As a result, aggregated data shown in the dashboard is an estimation since the intervals may not have the same top occurring endpoints or operations. The tables show approximate counts for the most commonly occurring endpoints or operations when the *Other* grouping appears.

//For example, when an endpoint occurs more often than other endpoints in one interval but occurs less often in another interval (thus sorting it into the *Other* group for that interval), the resulting table displays lower than actual values for that endpoint, since the metrics that do not appear are grouped into the *Other* group.


////
== Collecting Metrics for Entities

[[automatic-interval]]
=== How Data is Aggregated in Intervals

include::partial$data-aggregation.adoc[]

[[average-response-times-app]]
=== Charting Inactivity for Average Response Time

include::partial$average-response-time.adoc[]

[[endpoint-operation-metrics]]
=== Gathering Endpoint and Operation Use Metrics

include::partial$endpoint-operation-metrics.adoc[]

////
