= Anypoint Custom Metrics Connector

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The Anypoint Custom Metrics connector enables you to send operational and business metric values from a hybrid application to Anypoint Monitoring, where the metrics can be visualized in real time using the built-in *Custom metrics* dashboard. 

Once you select the metrics to display in the dashboard, you can filter and group the metrics along the included dimensions. You can include multiple custom and built-in metrics in a single dashboard visualization.

[NOTE] 
====
To use the Anypoint Custom Metrics connector, you must have a Titanium subscription. +
This feature is currently supported only for hybrid applications.
====

== Use the Custom Metrics Dashboard

Custom metrics are not collected for the application until you configure the Custom Metrics connector in your application flow and deploy the application to a server or server cluster. 

. In Anypoint Monitoring, select the application to view metrics for, and click *View*. 
. Click the *Custom metrics* tab. +
[NOTE]
You must select a hybrid application (application deployed to an on-premises server and managed in the cloud) to see the *Custom metrics* tab. +
If the Custom Metrics connector has collected one or more metrics in the last 24 hours, one chart per defined metric is displayed. 
. Click *Select a measurement for this chart* to display the measurement for the chart.
. Use the drop-down lists at the bottom of the chart to filter the data by: +
* *Aggregation* - Possible aggregations include:
** *None* (default) - No data aggregation.  
** *count* - Displays the total number of items collected for the measurement.
** *distinct* - 
** *integral* - 
** *mean* -
** *median* - Displays the middle value for the collected metrics.
** *mode* - Displays the most frequent value in the metrics collected for the defined. measurement. 
** *sum* - Displays the sum of numbers returned by the defined measurement. 
* *Measurement* - The choices in this list are determined by the measurement values you define in the Custom Metrics connector. 
* *Group by* - The choices in this list are determined by the values you define in the Custom Metrics connector. 


=== See Also

* xref:connectors::metrics/custom-metrics-connector.adoc[Custom Metrics Connector] 
* xref:connectors::metrics/custom-metrics-connector-reference.adoc[Custom Metrics Connector Reference]