= Using Built-in API Dashboards
:page-alias: api-analytics-dashboard
:note-flex-deployments-not-supported: This metric is not supported for APIs deployed through Flex Gateway.

The API dashboards provide charts to monitor API usage, which gives you insight into how your APIs are used and how they are performing.

If you have xref:api-manager::api-auto-discovery-new-concept.adoc[enabled API auto-discovery], your API metrics are available in the API dashboards in Anypoint Monitoring.

The enhanced metrics view includes detailed information about your APIs, and charts are sorted into dashboards based on the type of data displayed.

Charts displaying the `Last 1 hour` label show data that was collected during the past 60 minutes, starting with the current time.

[NOTE]
For xref:index.adoc#plans-legacy[Gold and Platinum subscriptions], Anypoint Monitoring retains API metrics data for 30 days. API Manager retains API metrics data for 30 days.

== Supported Versions of Mule Runtime Engine

include::partial$include-supported-mule-runtime-version.adoc[]

== View the API Dashboard

include::partial$include-nav-steps-no-permissions.adoc[]

. In the sidebar, click *Built-in dashboards*. 
. In *Built-in dashboards*, select the *Environment*, *Resource name*, and *Version/Instance* for the API to view.
. Click *View*. 
+
On the dashboard, you can view information about a running, managed API. 
. Select the date and time range to view the statistics for and click *Confirm*.

[[enhanced-api-metrics]]
== Enhanced Metrics View for API Dashboards

API dashboards provide you with various pages from which you can view different types of charts.

The following charts are available in the enhanced metrics view for APIs:

[%header,cols="1,4"]
|===
| API Dashboards | Charts

| <<overview-charts>> a|

* Request Volume
* Failed Requests
* Total 4xx Errors
* Total 5xx Errors
* Policy Violations
* Average Response Time

| <<requests-charts>> a|

* Requests
* Requests by Method
* Requests by Response Code
* Requests by Request Size
* Requests by Response Size

| <<failures-charts>> a|

* Failures
* Failures by Method
* Requests by Response Code
* Requests by Request Size
* Requests by Response Size

| <<performance-charts>> a|

* Requests by Performance
* Slow Requests +
include::reuse::partial$billing/pricing.adoc[tag=availabilityParenthetical]

| <<client-applications-charts>> a|

* Requests by Client ID
* Requests by Client IP
* Requests by Location

|===

[[overview-charts]]
=== Overview Charts

The following charts appear on the *Overview* dashboard:

Request Volume:: The sum of requests in the selected time period for the given API. Data is aggregated in one minute increments.

Failed Requests:: The sum of failed requests in the selected time period for the given API. Data is aggregated in one minute increments.

Total 4xx Errors:: The sum of 400 errors (such as 404, 408, and so on) in the selected time period for the given API.

Total 5xx Errors:: The sum of 500 errors (such as 500, 502, and so on) in the selected time period for the given API.

Policy Violations:: The sum of requests for policy violations in the selected time period, grouped by policy violation ID. Data is aggregated in one minute increments.

Average Response Time:: The average response time of requests in the selected time period for the given API. Data is aggregated in one minute increments.

[[requests-charts]]
=== Requests Charts

The following charts appear on the *Requests* dashboard:

Requests:: The sum of requests in the selected time period, grouped by the top N paths. By default, N is 100.
+
* If you select a time range within the last hour, data is aggregated in one minute increments.
* If you select a time range within the last day, data is aggregated in ten minute increments.
* If you select a time range that is larger than one day, data is aggregated in one hour increments.
+
[NOTE] 
--
{note-flex-deployments-not-supported}
--

Requests by Method:: The sum of requests in the selected time period, grouped by method. Data is aggregated in one minute increments.

Requests by Response Code:: The sum of requests in the selected time period, grouped by response code. Data is aggregated in one minute increments.

Requests by Request Size:: The sum of requests in the selected time period, grouped by request size. Data is aggregated in one minute increments.

Requests by Response Size:: The sum of requests in the selected time period, grouped by response size. Data is aggregated in one minute increments.

[[failures-charts]]
=== Failures Charts

The following charts appear on the *Failures* dashboard:

Failures:: The sum of failed requests in the selected time period, grouped by the top N paths. By default, N is 100.
+
* If you select a time range within the last hour, data is aggregated in one minute increments.
* If you select a time range within the last day, data is aggregated in ten minute increments.
* If you select a time range that is larger than one day, data is aggregated in one hour increments.
+
[NOTE] 
--
{note-flex-deployments-not-supported}
--

Failures by Method:: The sum of failed requests in the selected time period, grouped by method. Data is aggregated in one minute increments.

Requests by Response Code:: The sum of failed requests in the selected time period, grouped by response code. Data is aggregated in one minute increments.

Requests by Request Size:: The sum of failed requests in the selected time period, grouped by request size. Data is aggregated in one minute increments.

Requests by Response Size:: The sum of failed requests in the selected time period, grouped by response size. Data is aggregated in one minute increments.

[[performance-charts]]
=== Performance Charts

These charts appear on the *Performance* dashboard:

Requests by Performance:: The average request response times, grouped by path.
+
* If you select a time range within the last hour, data is aggregated in one minute increments.
* If you select a time range within the last day, data is aggregated in ten minute increments.
* If you select a time range that is larger than one day, data is aggregated in one hour increments.
+
[NOTE] 
--
{note-flex-deployments-not-supported}
--

Slow Requests:: The average response times that are greater than one second, grouped by path. +
include::reuse::partial$billing/pricing.adoc[tag=apiChartAvailability]
+
* If you select a time range within the last hour, data is aggregated in one minute increments.
* If you select a time range within the last day, data is aggregated in ten minute increments.
* If you select a time range that is larger than one day, data is aggregated in one hour increments.
+
[NOTE] 
--
{note-flex-deployments-not-supported}
--

[[client-applications-charts]]
=== Client Applications Charts

The following charts appear on the *Client Applications* dashboards:

Requests by Client ID:: The sum of requests in the period, grouped by client ID. Data is aggregated in one minute increments.

Requests by Client IP:: The sum of requests in the period, grouped by client IP address.
+
* If you select a time range within the last hour, data is aggregated in one minute increments.
* If you select a time range within the last day, data is aggregated in ten minute increments.
* If you select a time range that is larger than one day, data is aggregated in one hour increments.
+
[NOTE] 
--
{note-flex-deployments-not-supported}
--

Requests by Location:: The sum of requests during the time period specified, grouped by country. Data retention for the Requests by Location chart is one hour.
+
[NOTE] 
--
{note-flex-deployments-not-supported}
--

For information about chart metric collection, including the chart group *Other*, see xref:app-dashboards.adoc#endpoint-operation-metrics[How Endpoint and Operation Use Metrics Are Gathered].

[[endpoint-operation-metrics]]
==  Endpoint and Operation Metrics Collection (Other Group)

include::partial$endpoint-operation-metrics.adoc[]

== Anypoint Monitoring Archive API

include::partial$archive-api.adoc[]

[[average-response-times-api]]
== Charting Inactivity for Average Response Time

include::partial$average-response-time.adoc[]

== See Also

https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/anypoint-monitoring-archive-api/minor/1.0/pages/home/[Anypoint Monitoring Archive API]
