= Exploring Entity Metrics

Anypoint Monitoring collects metrics on each _entity_, such as an app or API, in Anypoint Platform. The *Entities Overview* page enables you to see data for your apps and APIs at a glance. You can filter the entities that appear in the *Entities Overview* page using attributes and elements. You can view up to 30 days of data at once, or you can specify dates and times to see only data from a shorter time period.  

include::partial$include-monitoring-metrics-collection.adoc[leveloffset=+1]

== Supported Versions of Mule Runtime Engine

include::partial$include-supported-mule-runtime-version.adoc[]

== Before You Begin



== Access the Entities Overview Page

include::partial$include-nav-steps-no-permissions.adoc[]

include::partial$include-nav-entities.adoc[]

The *Entities Overview* page appears, showing a summary of data 

== Filtering Data in the Entity Overview Page

By default, the *Entity Overview* page shows data for entities in your current business group and environment. You can change or remove these filters to see data for entities that are in different environments or business groups by clicking the *X* next to each option.

Quick filters, such as `Top 10 entities with highest error volume`, offer you common scenarios at a glance, but you can also use attributes and metrics to filter content that appears in the *Entity Overview* page. You can combine diffrent filters to capture specific combinations of data. 

You can filter entities using the following attributes: 

* Environment 
* Entity Name 
* Entity Type 
* Status
* Response time 
* Requests
* Errors 
* Client App (for API)
* Locations (for API)
* Org ID 
* Tag 

You can filter entities with the following metrics:

=== Applying Filters to the Entities Overview

include::partial$include-nav-steps-no-permissions.adoc[]

include::partial$include-nav-entities.adoc[]

. In the filter bar, enter an attribute, element, business group, or environment you want to use to filter your data.

== Filtering Data using the Time Period Selector

// steal Setting Data Display Options in a Dashboard and Setting the Time Period Display from dashboards-using.adoc but change the titles.

// see if Changing the Time Period to Display still applies.

// steal Refreshing Data


== Collecting Metrics for Entities

// use the pieces on how data is collected from Built-in Dashboards.

== Defining Metrics for Entities

//define metrics by stealing definitions from built-in dashboards metrics

// yes, the whole list.

[[automatic-interval]]
== How Data is Aggregated in Intervals

include::partial$data-aggregation.adoc[]

[[average-response-times-app]]
== Charting Inactivity for Average Response Time

include::partial$average-response-time.adoc[]

[[endpoint-operation-metrics]]
== How Endpoint and Operation Use Metrics Are Gathered

include::partial$endpoint-operation-metrics.adoc[]
