= Integration Intelligence 
:page-notice-banner-message: Open Beta Release: Integration Intelligence is in open beta. Any use of features in the beta state is subject to the applicable beta services terms and conditions.


Use Integration Intelligence (beta) to efficiently monitor, analyze, and troubleshoot your data by bringing your MuleSoft telemetry data into the Salesforce ecosystem, unlocking a new, unified observability experience:

Integration Intelligence provides:

* Enhanced visibility into your MuleSoft telemetry data by creating a new data tier that overcomes limitations of endpoint monitoring.

* Unified data storage by bringing your MuleSoft telemetry data, including metrics, logs, and traces, into Salesforce Data Cloud. Thisensures better data retention and centralized access for analysis.

* Targeted data ingestion for the specified Business Group. You can also select an initial ingestion timeframe (such as 1, 2, or 4 weeks) for historical data backfill, providing you with immediate historical context for analysis.

* Advanced visualization with Tableau Next. Using Data Cloud and Tableau Next, you can transform how you analyze integration performance. Tableau Next serves as the primary experience tier for visualizing your data. 

* Out-of-the-Box Dashboards with pre-configured pages within a new Integration IntelligenceLightning App in Salesforce, featuring dashboards for:
** App Insights, offering a unified view of application metrics, health, and usage.
** API Insights, providing a unified view of all API metrics, including Flex APIs, encompassing health and usage.
** Logs and Traces, enabling you to view tabular pages of log events (including filtering capabilities for timeframe/log level) and traces.

* Seamless cross-platform access with seamless login (SSO) removes barriers between Anypoint Platform and Salesforce, enabling faster access to troubleshooting data.

* Single-click navigation means you can gain deeper insights directly from  the Anypoint Platform Monitoring *Insights* page. 

== What's Next

* xref:integration-intelligence-setup.adoc[Set up Integration Intelligence]
* xref:integration-intelligence-dashboards.adoc[Dashboards]: Monitor Mule apps and APIs, and get business insights
* xref:integration-intelligence-dashboards.adoc[Logs]: TODO_TODO


== See Also
