= Log Tokenization

[NOTE]
A Titanium subscription is required to use this feature. 

App metrics are collected and forwarded to Anypoint Monitoring, where you can manage and search the logs in the Anypoint Monitoring log management console. Log tokenization provides an extra layer of security for logs that may contain sensitive data. 

Log messages are often difficult to parse in order to apply meaningful tokenization because they can have so many different formats. The tokenization service connector helps you tokenize logs by parsing the unstructured content of logs to find the break points so that log messages can be broken into meaningful tokens. You can leverage the Anypoint Security tokenization service, which runs in Runtime Fabric, to tokenize and detokenize Mule app logs. 

== Supported Mule Versions

Log tokenization is supported on:

* Hybrid apps running on Mule 3.x or 4.x
* CloudHub apps running on Mule 3.x or 4.x  

== Prerequisites

. xref:1.2@runtime-fabric::install-create-rtf-arm.adoc[Install Runtime Fabric].
. xref:1.2@runtime-fabric::enable-inbound-traffic.adoc[Enable inbound traffic] on Runtime Fabric. 
. In Anypoint Security, xref:anypoint-security::tokenization-formats.adoc[create a tokenization format].
. In Anypoint Security, xref:anypoint-security::create-tokenization-service.adoc[create the tokenization service]. 
. In API Manager, xref:2.x@api-manager::getting-started-proxy.adoc[set up the API gateway] for the Mule app to serve as the proxy.

== Add the Connectors

To enable log tokenization, you need to create an app flow using Flow Designer or Studio and add the required components. 

. In Flow Designer or Studio, create an app flow for the Mule app. 
. On Exchange, search for the following components, and add them to your Mule app flow. +
* Logger connector
* Tokenization Service connector
* Tokenization Service API
. In Anypoint Monitoring, click *Log Search* in the menu on the left. +
On the log search page, you can search for the tokenized values. 
. To detokenize a value, go to API Manager. See xref:2.x@api-manager::policy-mule4-detokenization.adoc[Detokenization Policy] +
[NOTE]
You must have the *Manage Policies* permission to detokenize values. See xref:2.x@api-manager::environment-permission-task.adoc[Granting Permission to Access an Environment]

== See Also

* xref:exchange::index.adoc[Anypoint Exchange]
* xref:design-center::about-designing-a-mule-application.adoc[Flow Designer]
* xref:anypoint-security::tokenization.adoc[Tokenization Service]
* xref:2.x@api-manager::policy-mule4-tokenization.adoc[Tokenization Policy]






