= Anypoint Monitoring Log Points

The Log Points feature in Anypoint Monitoring allows you to generate logs for apps and APIs in real-time and without writing code. For apps, you can specify the level of logs you want to generate, and for APIs, you can specify properties for the logs. You can generate these logs without restarting your application. 

== Log Points for Apps

The Log Points feature for apps enables you to log information from connectors in any Mule app in real-time. If you are using one of the supported connectors, you can select a log level (debug, info, warn, or error) and generate logs.

=== Prerequisites

To use this feature, you must have the following:

* A https://www.mulesoft.com/anypoint-pricing[Titanium subscription] to Anypoint Monitoring and Mule 3.8.5 or later
* The *Runtime Manager > Manage Settings* permission

=== Supported Connectors

The following Anypoint Connectors are available for use with the Log Points feature.

.Supported Connectors
|===
|Supported Anypoint Connectors |Supported for Mule 3.x |Supported for Mule 4.x

|Amazon S3
|x
|x

|Amazon SQS
|x
|x

|Database
|x
|x

|Email
|x
|x

|File
|x
|x

|FTP
|x
|x

|IBM MQ
|
|x

|JMS
|x
|x

|Microsoft Service Bus
|x
|x

|MongoDB
|x
|x

|MQ
|x
|x

|Object Store
|x
|x

|Salesforce
|x
|x

|SFTP
|x
|x

|Sockets
|
|x

|TCP
|x
|

|UDP
|x
|

|VM Transport
|x
|x

|WMQ
|x
|

|===

=== Supported Mule Versions

* Mule 3 versions 3.8.5 and later
* Mule 4 versions 4.1.1 and later


=== Enable App Log Points

. Log in to Anypoint Platform and navigate to Anypoint Monitoring. 
. In the Anypoint Monitoring navigation menu, click *Log Points*.
. Select the following: +
* *Environment*: The environment in which the app is running.
* *Resource name*: The name of the app.
. Click *Select*.
. Select the connectors for which you want to generate logs.
. Select a log level for each connector.
. Click *Save & Apply*. +
A message that your configuration has been applied appears at the top of the page with a *View API Logs* link. The logs might take a moment to appear.
. Click the *View Logs* link to view the logs for the selected log point.

[NOTE]
If you select either the trace or debug log level, disable log point monitoring when you are finished, to avoid slowing your application's performance.

== Log Points for APIs

The Log Points feature for APIs enables you to interactively extract data from running managed APIs. You can specify properties of your managed API (for example, the host and method in the request header) for which to generate logs without having to write code or redeploy your application. This helps you troubleshoot without having to restart the application.

For example, you can specify a cookie header in an API to see if an injection attack is in progress. The log data for the specified cookie header is automatically displayed in real time on the Logs page.

=== Prerequisites

To use this feature, you must have the following:

* A https://www.mulesoft.com/anypoint-pricing[Titanium subscription] to Anypoint Monitoring and Mule 3.8.5 or later
* The *API Manager > Manage Policies* permission

=== Supported APIs

The following types of API are available for use with the Log Points feature:

* Basic endpoint APIs (CloudHub and hybrid)
 ** CloudHub
 ** Hybrid
* Endpoint with Proxy APIs
  ** CloudHub proxy
  ** Hybrid proxy

[NOTE]
All basic endpoint APIs are displayed in the selectors regardless of whether the registered API has a supported Mule runtime engine version. If you save a log point for a basic endpoint API with an unsupported version, the application policy fails.

=== Supported Mule Versions

* Mule 3 versions 3.8.5 and later
* Mule 4 versions 4.1.1 and later

=== Enable API Log Points

. Sign into Anypoint Platform and navigate to Anypoint Monitoring.
. In the Anypoint Monitoring navigation menu, click *Log Points*.
. Select the following: +
* *Environment*: The environment the API is running in.
* *Resource name*: The name of the API.
* *Version/Instance*: The version and instance of the API.
. Click *Select*.
. Select the *Request* points to log and monitor. +
You can monitor the following request header log points: +
* *User Agent*
* *Path*
* *Host*
* *Method*
* *Remote Access*
* *Accept*
* *Accept Encoding*
* *Accept Language*
* *Cookie*
* *Referrer* +
You can click the blue box to the left of *Header*, to select all log points. +
Select *Body* to monitor the *Request Body*.
. Select the *Response* points to log and monitor. +
You can monitor the following request header log points: +
* *Status Code*
* *Connection*
* *Date*
* *Set-Cookie*
* *Pragma*
+
You can click the blue box to the left of *Header* to select all log points.
Select *Body* to monitor the *Response Body*.
. Click *Save & Apply*. +
A message that your configuration has been applied appears at the top of the page with a *View API Logs* link.
The logs might take a moment to appear.
. Click the *View API Logs* link to view the logs for the selected log point. +

[NOTE]
When you are finished monitoring API log points, disable log point monitoring to avoid slowing your application's performance.
