= Using Logs in Anypoint Monitoring (Canada and Japan)
:page-notice-banner-message: <b>Pilot release</b>: This feature is for a Pilot release in Canada and Japan Cloud instances of Anypoint Platform. 

//feature tier:
include::partial$subsection-pills.adoc[tag="anypoint-cloud-support-advanced-only"]

In the https://ca1.platform.mulesoft.com/monitoring[Canada] and  https://jp1.platform.mulesoft.com/monitoring[Japan] Clouds, search for up to 30 days of logs across apps deployed to one of your organization's environments. Logs provide the time, log level, and expandable message details.

TODO: IMAGE HERE

== Search for Logs

. Select a time and date range, from the last 15 minutes to the last 30 days.
+
Custom selections are available for up to the last 30 days of logs and for selected time ranges. 
. Select an environment.
. Provide a <<ref-query, log query>>.
. Review the search results.
+
You can expand the message to get message details.
+
If no data returns, try a different date-time range, query, or environment. 

== View the Latest Data

To review the latest log data, click the Refresh button. 

== Environments

When displaying logs, select the environment that contains the logs you intend to review.

Built-in xref:access-management::environments#types-of-environments.adoc[environments] are:

* *Environment: Design*
* *Environment: Production*
* *Environment: Sandbox*

Any other environments that your organization xref:access-management::environments.adoc#to-create-a-new-environment[creates] are also available.

[[ref-query]]
== Log Query Reference

Use filters to narrow the results of your search for logs. The filters match values of fields in the logs:

* `application` accepts an *=* operator followed by an application name.
//TODO: TBD IF *TRACE* IS ALSO A VALID LOG LEVEL
* `log_level` accepts an *=* operator followed by a value *INFO*, *WARN*, *CRITICAL*, *FATAL*, or *DEBUG* 
* `message` accepts a *LIKE* operator for partial or exact matches in log `message` fields. 

Search query rules:

* Each filter allows a single value. 
* You can use any or all of the available filters in your query.
+
Multiple filters in a query are processed as logical ANDs (and not as ORs), meaning that searches return data matching all the filter criteria, not just some of it. 
* Multiple filters of the same type, such as two `application` filters, aren't allowed. 
* Quotation marks around search strings aren't necessary. 