= Managing CloudHub and Hybrid Settings 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

On the *Settings* page in Anypoint Monitoring, you can:

* Find the instructions to install Anypoint Monitoring on an on-premises server to monitor Mule applications running on that server.
* Enable (or disable) monitoring for applications running on Mule.

== Access the Settings Page

To access the *Settings* page, you must have the Anypoint Monitoring User and the Runtime Manager - Read Applications permissions. See xref:access-management::users#granting-permissions-and-roles-to-users[Granting Permissions and Roles to Users].

include::partial$include-nav-steps-no-permissions.adoc[]

. In the Anypoint Monitoring navigation menu, click *Settings*. 
. To monitor applications deployed to a local server, select *Hybrid*, and follow the procedure to install Anypoint Monitoring agent from the latest version of the agent's installer in `am.zip`. 
+
//TODO: TEMPORARY UNTIL WE have a better location for earlier versions
To use an earlier version, see the knowledge article https://help.salesforce.com/s/articleView?id=004576938&type=1[Unable to Download Anypoint Monitoring Agent Installer for Windows after April 1st, 2025 from Anypoint Monitoring UI]. 
. To enable (or disable) monitoring for apps deployed to CloudHub, select *CloudHub*.

[NOTE]
Anypoint Monitoring is enabled by default for all CloudHub 2.0 applications.

== See Also

* xref:am-installing.adoc[Install Anypoint Monitoring On-Premises]
* xref:configure-monitoring-cloudhub.adoc[Configure Anypoint Monitoring for Mule Apps]
