= Getting Performance Metrics from Connectors
:page-info-pills: anypoint-pricing-titanium

View performance metrics for supported connectors in your Mule apps in Anypoint Monitoring dashboards. Built-in dashboards and Anypoint Insights support these connector metrics.

//TODO: THIS PAGE NEEDS AN UPDATE -- ALL CONNECTORS WILL BE JAVA 17 AT SOME POINT

== Supported Mule Versions

To monitor connectors, you must use a xref:release-notes::mule-runtime/mule-esb.adoc[supported Mule version] for your apps: 

* Hybrid deployments
* CloudHub and CloudHub 2.0 deployments
//TODO: RTF DEPLOYMENTS
//* Runtime Fabric deployments

//NOTE: Standard support for Java 8 and 11 ends in August 2026 for 4.6 LTS.
NOTE:If your app is using Java 17, you must specify the version during deployment. For a list of compatible connectors, see https://help.salesforce.com/s/articleView?language=en_US&id=000782248&type=1[Java 17 Compatible Anypoint Connectors].

== Supported Connectors

The type of connector determines the charts that are displayed. Unless otherwise specified, the following metrics are for outbound requests only.

[%header,cols="1,4"]
|===
| Connector | Charts
|*Anypoint MQ (Inbound)* a|

* Requests: Average number of Anypoint MQ connector inbound requests, grouped by operation and automatic intervals
* Response Time: Average response time of Anypoint MQ connector inbound requests, grouped by operation and automatic intervals
* Failures: Average number of Anypoint MQ connector inbound request failures, grouped by operation and automatic intervals

|*Anypoint MQ (Outbound)* a|

* Requests: Average number of Anypoint MQ connector outbound requests, grouped by operation and automatic intervals
* Response Time: Average response time of Anypoint MQ connector outbound requests, grouped by operation and automatic intervals
* Failures: Average number of Anypoint MQ connector outbound request failures, grouped by operation and automatic intervals
|*Database* a|

* Requests: Average number of Database connector requests, grouped by automatic intervals
* Response Time: Average response time of Database connector requests, grouped by automatic intervals
* Failures: Average number of Database connector request failures, grouped by automatic intervals
|*FTP* a|

* Requests: Average number of FTP connector requests, grouped by automatic intervals
* Response Time: Average response time of FTP connector requests, grouped by automatic intervals
* Failures: Average number of FTP connector request failures, grouped by automatic intervals
|*HTTP* a|

* Requests: Average number of HTTP connector requests, grouped by automatic intervals
* Response Time: Average response time of HTTP connector requests, grouped by automatic intervals
* Failures: Average number of HTTP connector request failures, grouped by automatic intervals
|*Object Store* a|

* Requests: Average number of Object Store connector requests, grouped by operation and automatic intervals
* Response Time: Average response time of Object Store connector requests, grouped by operation and automatic intervals
* Failures: Average number of Object Store connector request failures, grouped by operation and automatic intervals
|*Salesforce* a|

* Requests: Average number of Salesforce connector requests, grouped by automatic intervals
* Response Time: Average response time of Salesforce connector requests, grouped by automatic intervals
* Failures: Average number of Salesforce connector request failures, grouped by automatic intervals
|*SFTP* a|

* Requests: Average number of SFTP connector requests, grouped by automatic intervals
* Response Time: Average response time of SFTP connector requests, grouped by automatic intervals
* Failures: Average number of SFTP connector request failures, grouped by automatic intervals

//TODO: EMAIL SUBMIT METRICS TO MONITORING STILL? ( Mule 4 EMAIL CONNECTOR merges SMTP, IMAP, and POP3)
//|*SMTP* a|
//
//* Requests: Average number of SMTP connector requests, grouped by automatic intervals
//* Response Time: Average response time of SMTP connector requests, grouped by automatic intervals
//* Failures: Average number of SMTP connector request failures, grouped by automatic intervals
|*Web Services* a|

* Requests: Average number of Web Services connector requests, grouped by automatic intervals
* Response Time: Average response time of Web Services connector requests, grouped by automatic intervals
* Failures: Average number of Web Services connector request failures, grouped by automatic intervals
|*Other* a|

The connector type "Other" is any connector not specified in this table.

* Requests: Average number of requests of connectors of type Other, grouped by automatic intervals
* Response Time: Average response time of requests of connectors of type Other, grouped by automatic intervals
* Failures: Average number of request failures of other types of connectors, grouped by automatic intervals
|===


== Access Connector Monitoring

include::partial$include-nav-steps-no-permissions.adoc[]

. Open *Insights* or *Built-in dashboards*.
. Navigate to a Mule app that uses a supported connector.
. In the detail page for the app, click *Connectors* to view connector metrics.
+
include::reuse::partial$billing/pricing.adoc[tag=connectorTabReq]
