= Anypoint Monitoring Settings
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Use the Settings page to install Anypoint Monitoring on an on-premises server to monitor applications running on that server, and enable (or disable) monitoring for applications running on Mule 3.9.2.

== View the Settings Page

To see the *Settings* page, you must:

* Have the Anypoint Monitoring User permission. See xref:access-management::users#granting-permissions-and-roles-to-users[Granting Permissions and Roles to Users].
* Have on-premises monitoring for hybrid deployments enabled at your master org level. Check with your account representative to verify this.

. Sign into Anypoint Platform and navigate to *Anypoint Monitoring*.
. In the menu on the left, click *Settings*. +
. To xref:am-installing.adoc[install Anypoint Monitoring on-premises], select *Hybrid*. +
The instructions for installing Anypoint Monitoring on-premises are displayed. You can also download the Anypoint Monitoring installation ZIP (`am.zip`) file from this page. 
. To enable (or disable) monitoring for apps deployed to CloudHub, select *CloudHub*.

== Enable Monitoring for Apps Deployed to CloudHub

You can enable monitoring for Mule apps running on Mule 3.9.2 in the xref:monitoring_settings_page.adoc[Settings page]. 

. Sign into Anypoint Platform and navigate to *Anypoint Monitoring*.
. In the menu on the left, click *Settings*. 
. Select *CloudHub*. 
. In the *Environment* drop-down list, select the environment where the application is running. +
A list of running applications is displayed for the selected environment. +
You can search for a specific application using the *List of resources* search box.
. Next to the application click *Enable* to enable monitoring for the application, or *Disable* to disable monitoring for the application. 
