= Anypoint Monitoring Performance Impact, Limits, and Data Retention

Anypoint Monitoring processes and retains massive amounts of data with a low performance impact. Titanium subscribers receive an enhanced data retention package and more storage than Gold and Platinum subscribers. For better performance and readability, your log data is truncated into short lines.

You can also improve your Anypoint Monitoring experience by adjusting your screen resolution.


== Mule Monitoring Agent Performance Impact

Based on typical use, the expected CPU utilization from the Mule monitoring agent is less than 5%. For more information, refer to xref:monitoring::configure-monitoring-cloudhub#performance-impact[Configure and Enable Anypoint Monitoring for Mule Apps (CloudHub)].

Anypoint Monitoring asynchronously collects data at a resolution of one minute, which does not block Mule runtime data processing.

== Data Retention and Limits

=== Anypoint Integration Starter Package Limits

Organizations that have the Anypoint Integration Starter package receive modest data retention and feature limits:

Logs::
Log limits are documented in xref:runtime-manager::viewing-log-data.adoc#log-persistence[Runtime Manager].

Application metrics::
30 days.

Enhanced API metrics::
30 days. The limit for data in the *Client Applications* tab is 1 hour.

Basic alerts for servers and Mule apps::
Six per server or app. 

Basic alerts for APIs::
Six per API instance.

=== Anypoint Integration Advanced Package Limits

Organizations that have the Anypoint Integration Advanced package receive more robust data retention and feature limits:

Logs::
In raw format, your logs can occupy as much space as you receive with your pricing package. Note that the storage space you receive with your pricing package is used to store logs and metrics data. Because metrics do not take up much storage capacity, you can use the majority of your storage for raw log data.

Searchable logs::
You receive additional storage that is 10% of the size of purchased storage for indexes for searchable logs. +
Anypoint Monitoring creates indexes on raw logs to enable you to efficiently and quickly perform log search queries. Anypoint Monitoring indexes the most recent logs for searching, up to 10% of the total purchased storage size. You can download logs to access older logs.

Application metrics::
365 days.

Enhanced API metrics::
30 days. The following limits also apply:
* Data in the *Client Applications* tab is limited to 1 hour.
* Data from *api_path_metric* and *api_client_ip_metric* tables in advanced mode of custom dashboards is limited to 1 hour.

Custom metrics::
365 days in production environments.

Advanced alerts::
10 per app or API instance.

Basic alerts for servers and Mule apps::
10 per server or app.

Basic alerts for APIs::
10 per server or app.

=== Gold and Platinum Subscription Limits

Gold and Platinum subscribers to Anypoint Platform receive modest data retention and feature limits:

Logs::
Log limits are documented in xref:runtime-manager::viewing-log-data.adoc#log-persistence[Runtime Manager].

Application metrics::
30 days.

Enhanced API metrics::
30 days. The limit for data in the *Client Applications* tab is 1 hour.

Basic alerts for servers and Mule apps::
50 basic alerts.

Basic alerts for APIs::
Six basic alerts per API instance.

=== Titanium Subscription Limits

Titanium subscribers to Anypoint Platform receive more robust data retention and feature limits:

Logs::
In raw format, your logs can occupy as much space as you receive with your Titanium subscription. Note that the storage space you receive with your Titanium subscription is used to store logs and metrics data. Because metrics do not take up much storage capacity, you can use the majority of your storage for raw log data.

Searchable logs::
You receive additional storage that is 10% of the size of purchased storage for indexes for searchable logs. +
Anypoint Monitoring creates indexes on raw logs to enable you to efficiently and quickly perform log search queries. Anypoint Monitoring indexes the most recent logs for searching, up to 10% of the total purchased storage size. You can download logs to access older logs.

Application metrics::
365 days.

Enhanced API metrics::
30 days. The following limits also apply:
* Data in the *Client Applications* tab is limited to 1 hour.
* Data from *api_path_metric* and *api_client_ip_metric* tables in advanced mode of custom dashboards is limited to 1 hour.

Custom metrics::
365 days in production environments.
// future: 30 days storage only for Sandbox - this is currently not implemented. We can either skip this part, or we can document 30 days which is future looking

Advanced alerts::
20 per parent organization.

Basic alerts for servers and Mule apps::
50 times the number of production vCores in your organization plus 100. For example, an organization that has 2 production vCores and a Titanium subscription has a limit of 200 basic alerts. Note that you can also use your alert allowance for sandbox deployments, but this limit subject to the overall xref:access-management::business-groups.adoc#redistribute-resources[production vCore limit].

Basic alerts for APIs::
Ten basic alerts per API instance.

Telemetry Exporter Connections::
10 per organization.

== Logging Data Management

When you manage logs, the maximum length of one line of log data is 8 KB (including date and thread metadata). Single lines that are longer than 8 KB are truncated at the 8 KB mark.

To log longer segments of information, you must split them up into chunks that are individually smaller than 8 KB.

== Screen Resolution

Use a minimum screen resolution of 1024 by 768 pixels.
