= Anypoint Monitoring Performance, Impact, and Limits

Review details about the performance impact and data retention with Anypoint Monitoring.

== Mule Monitoring Agent Performance Impact

Based on typical usage, the expected CPU utilization is less than 5%. For more information, refer to xref:monitoring::configure-monitoring-cloudhub#performance-impact[Configure and Enable Anypoint Monitoring for Mule Apps (CloudHub)].

== Data Retention and Aggregation

Anypoint Monitoring asynchronously collects data, which does not block Mule runtime data processing.

* Minute Resolution for Metrics.
* Gold and Platinum subscriptions:
 ** API analytics metrics data are retained for 90 days.
 ** Application metrics data are retained for 30 days.


== Screen Resolution

For the best performance, use a minimum screen resolution of 1024x768.

== Logging

In Log Management, the maximum length of one line of log data is 8 KB (including date and thread metadata). Single lines that are longer than 8 KB will be truncated at the 8 KB mark.

To log longer segments of information, you must split them up into chunks that are individually smaller than 8 KB.
