= Understanding Performance Impact, Limits, and Data Retention
:data-cleanup: Metrics data can persist beyond the data retention period. The data is removed when the automated cleanup cycle takes place.

Anypoint Monitoring processes and retains massive amounts of data with a low performance impact. Titanium subscribers receive an enhanced data retention package and more storage than Gold and Platinum subscribers. For better performance and readability, your log data is truncated into short lines.

You can also improve your Anypoint Monitoring experience by adjusting your screen resolution.

For core-based subscription tier, see xref:index.adoc#plans-legacy[Anypoint Monitoring Features for Legacy Subscription-Based Plans].


== Mule Monitoring Agent Performance Impact

Based on typical use, the expected CPU utilization from the Mule monitoring agent is less than 5%. For more information, refer to xref:monitoring::configure-monitoring-cloudhub#performance-impact[Configure and Enable Anypoint Monitoring for Mule Apps (CloudHub)].

Anypoint Monitoring asynchronously collects data at a resolution of one minute, which does not block Mule runtime data processing.

== Data Retention Limits

Limits vary by xref:index.adoc#billing[subscription tier]:

* <<starter>>
* <<advanced>>
* <<gold-platinum>>
* <<titanium>>

[[starter]]
=== Anypoint Integration Starter Package Limits

Organizations that have the Anypoint Integration Starter package receive modest data retention and feature limits:

Logs::
Log limits are documented in xref:runtime-manager::viewing-log-data.adoc#log-persistence[Runtime Manager].

Application metrics::
30 days.

Enhanced API metrics::
30 days. Data in the *Client Applications* tab is limited to 1 hour.

Basic alerts for servers and Mule apps::
Six per server or app. 

Basic alerts for APIs::
Six per API instance.

[[advanced]]
=== Anypoint Integration Advanced Package Limits
//Retain extra info on Advanced package
Organizations that have the Anypoint Integration Advanced package receive more robust data retention and feature limits:

Logs::
In raw format, your logs can occupy as much space as you receive with your pricing package. Note that the storage space you receive with your pricing package is used to store logs and metrics data. Because metrics do not take up much storage capacity, you can use the majority of your storage for raw log data.


Searchable logs::
You receive additional storage that is 10% of the size of purchased storage for indexes for searchable logs.
+
Anypoint Monitoring creates indexes on raw logs to enable you to efficiently and quickly perform log search queries. Anypoint Monitoring indexes the most recent logs for searching, up to 10% of the total purchased storage size. You can download logs to access older logs. 
+
Total storage capacity is shared globally across all apps and is limited by the number of messages that your organization purchases and the maximum searchable storage allocation limit of 6TB.

* For every flow purchased, this subscription tier receives:
** 5GB of archival storage
** 0.5GB of searchable storage (10% of archival storage)
* For every 1M messages purchased, this subscription tier receives:
** 2.5GB of archival storage
** 0.25GB of searchable storage (10% of archival storage)

Application metrics::
365 days.

Enhanced API metrics::
30 days. These limits also apply:

* Data in the *Client Applications* tab is limited to 1 hour.
* Data from *api_path_metric* and *api_client_ip_metric* tables in advanced mode of custom dashboards is limited to 1 hour.
+
{data-cleanup}

Custom metrics::
365 days in production environments.

Advanced alerts::
10 per app or API instance.

Basic alerts for servers and Mule apps::
10 per server or app.

Basic alerts for APIs::
10 per server or app.

Telemetry Exporter Connections::
10 per organization.

[[gold-platinum]]
=== Gold and Platinum Subscription Limits

xref:index.adoc#plans-legacy[Gold and Platinum tier] subscribers to Anypoint Platform receive modest data retention and feature limits:

Logs::
Log limits are documented in xref:runtime-manager::viewing-log-data.adoc#log-persistence[Runtime Manager].

Application metrics::
30 days.

Enhanced API metrics::
30 days. These limits also apply:

* Data in the *Client Applications* tab is limited to 1 hour.
* Data from *api_path_metric* and *api_client_ip_metric* tables in advanced mode of custom dashboards is limited to 1 hour.
+
{data-cleanup}

Basic alerts for servers and Mule apps::
50 basic alerts.

Basic alerts for APIs::
Six basic alerts per API instance.

[[titanium]]
=== Titanium Subscription Limits

xref:index.adoc#plans-legacy[Titanium tier] subscribers to Anypoint Platform receive more robust data retention and feature limits:

Logs::
In raw format, your logs can occupy as much space as you receive with your Titanium subscription. Note that the storage space you receive with your Titanium subscription is used to store logs and metrics data. Because metrics do not take up much storage capacity, you can use the majority of your storage for raw log data.

Searchable logs::
You receive additional storage that is 10% of the size of purchased storage for indexes for searchable logs. +
Anypoint Monitoring creates indexes on raw logs to enable you to efficiently and quickly perform log search queries. Anypoint Monitoring indexes the most recent logs for searching, up to 10% of the total purchased storage size. You can download logs to access older logs.

* For each production vCore, this subscription tier receives:  
** 200GB of archival storage
** 20GB of searchable storage (10% of archival storage)
* For each pre-production vCore, this subscription tier receives: 
** 50GB of archival storage
** 5GB of searchable storage (10% of archival storage)

Application metrics::
365 days.

Enhanced API metrics::
30 days. These limits also apply:

* Data in the *Client Applications* tab is limited to 1 hour.
* Data from *api_path_metric* and *api_client_ip_metric* tables in advanced mode of custom dashboards is limited to 1 hour.
+
{data-cleanup}

Custom metrics::
365 days in production environments.
// future: 30 days storage only for Sandbox - this is currently not implemented. We can either skip this part, or we can document 30 days which is future looking

Advanced alerts::
20 per parent organization.

Basic alerts for servers and Mule apps::
50 times the number of production vCores in your organization plus 100. For example, an organization that has 2 production vCores and a Titanium subscription has a limit of 200 basic alerts. Note that you can also use your alert allowance for sandbox deployments, but this limit subject to the overall xref:access-management::business-groups.adoc#redistribute-resources[production vCore limit].

Basic alerts for APIs::
Ten basic alerts per API instance.

Telemetry Exporter Connections::
10 per organization.

== Logging Data Management

When you manage logs, the maximum length of one line of log data is 8 KB (including date and thread metadata). Single lines that are longer than 8 KB are truncated at the 8 KB mark.

To log longer segments of information, you must split them up into chunks that are individually smaller than 8 KB.

== Screen Resolution

Use a minimum screen resolution of 1024 by 768 pixels.

== Grace Period for Metrics Data Retention

If your organization downgrades to a lower subscription tier (usage-based or core-based) or cancels your subscription, your metrics data is removed according to this schedule:

* Downgrades: Approximately 14 days after a downgrade to a lower tier, an additional 21-day grace period takes place before your data is removed.
* Cancellations: Approximately 90 days after a cancellation, an additional 21-day grace period takes place before your data is removed.

To retrieve metrics data, you can use the https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/anypoint-monitoring-archive-api/minor/1.0/pages/Metric%20Data/[Anypoint Monitoring Archive API].