= Get Started
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Monitoring is the part of Management Center in Anypoint Platform that provides data on Mule apps that are running on CloudHub or an on-premises server. 

[[prereqs]]
== Before You Begin

To use Anypoint Monitoring, you must have an Anypoint Platform account with the required permission:

* Anypoint Monitoring User

Typically, administrators set permissions through Access Management. See xref:access-management::users.adoc#granting-permissions-and-roles-to-users[Granting Permissions and Roles to Users]. 

== Supported Versions of Mule Runtime Engine

include::partial$include-supported-mule-runtime-version.adoc[]

[[using_monitoring]]
== Set Up Anypoint Monitoring Tools

. Meet the prerequisites in <<prereqs>>.
include::partial$include-nav-steps-no-permissions.adoc[]
+
If you are unable to access or use Anypoint Monitoring, see <<required_permission>>.
. Find Anypoint Monitoring tools in Anypoint Platform:
+
include::monitoring::partial$include-features.adoc[tags="feature-list"]
. To set up custom dashboards or alerts, see:

* xref:dashboard-custom-config.adoc[Configuring Custom Dashboards]
* xref:alerts.adoc[Configuring Alerts]

. Enable Anypoint Monitoring for your host environment:

* <<enable-cloudhub>>


[[enable-cloudhub]]
=== Enable Anypoint Monitoring on CloudHub

To monitor a Mule app that is deployed to CloudHub, the app must run on a supported version of Mule runtime engine. See xref:configure-monitoring-cloudhub.adoc[Configure Anypoint Monitoring for Mule Apps (CloudHub)].

[[]]
=== Enable Anypoint Monitoring On-Premises

You can xref:am-installing.adoc[install Anypoint Monitoring] on an on-premises server to monitor Mule apps that are running on that server and managed via Runtime Manager (hybrid apps).





== See Also

* xref:monitoring-settings-page.adoc[Anypoint Monitoring Settings]
* xref:configure-monitoring-cloudhub.adoc[Configure Anypoint Monitoring for Mule Apps]
* xref:am-installing.adoc[Install Anypoint Monitoring On-Premises]
* xref:api-functional-monitoring::afm-create-monitor.adoc[Create a Monitor]
