= Getting Started
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Monitoring provides data on Mule apps, APIs, and  instances of agents, brokers, and MCP servers.

[NOTE]
Functional Monitoring is covered in xref:api-functional-monitoring::index.adoc[API Functional Monitoring].

== Supported Versions of Mule Runtime Engine

include::partial$include-supported-mule-runtime-version.adoc[]

[[using_monitoring]]
== Use Anypoint Monitoring

include::partial$include-nav-steps-no-permissions.adoc[]
+
If you do not find *Monitoring* or are unable to use Anypoint Monitoring, check your permissions (<<required_permission>>).

. From the sidebar, you can find and use the monitoring tools:
+
* xref:logs.adoc[Using Logs]
* xref:alerts.adoc[Alerts]

== Configurations

Custom dashboards and alerts require configuration before you can use them. For guidance, see:

* xref:dashboard-custom-config.adoc[Configuring Custom Dashboards]
* xref:alerts.adoc[Configuring Alerts]

[[required_permission]]
== Required Permission

xref:access-management::permissions-by-product.adoc#monitoring[Monitoring permissions] lists user and administrator permissions.

Typically, administrators set permissions through Access Management. See xref:access-management::users.adoc#granting-permissions-and-roles-to-users[Granting Permissions and Roles to Users].

[[runtime_versions]]
== Enable Anypoint Monitoring on CloudHub

For Anypoint Monitoring to start monitoring your Mule apps, you must deploy them to the appropriate version of Mule runtime engine.  See xref:configure-monitoring-cloudhub.adoc[Configure Anypoint Monitoring for Mule Apps (CloudHub)].

== Enable Anypoint Monitoring On-Premises

You can xref:am-installing.adoc[install Anypoint Monitoring] on an on-premises server to monitor applications that are running on that server and managed via Runtime Manager (hybrid apps).

[[access-key-metrics]]
== Access Key Metrics through the Anypoint Monitoring Agent

//intro
include::monitoring::partial$include-key-metrics-apim.adoc[tags=monitoring-agent-intro]

//
include::monitoring::partial$include-key-metrics-apim.adoc[tags=monitoring-agent-requirements]


== See Also

* xref:monitoring-settings-page.adoc[Anypoint Monitoring Settings]
* xref:configure-monitoring-cloudhub.adoc[Configure Anypoint Monitoring for Mule Apps]
* xref:am-installing.adoc[Install Anypoint Monitoring On-Premises]
* xref:api-functional-monitoring::afm-create-monitor.adoc[Create a Monitor]
