= Traces 

The Traces feature in Anypoint Monitoring enables you to observe requests for apps and APIs as they travel across services. _Traces_ describe the journey that the requests make throughout their pipelines of services. Each trace originates from an _entity_, such as an app or API, that is available in Anypoint Platform. The *Traces* overview page enables you to see a list of traces that are currently available in Anypoint Platform. You can use this data to troubleshoot requests that have errors or slow response times, optimize your resource allocation, and track your entity requests end-to-end. For example, an Ops administrator could use traces to search for a specific transaction and have a visualization for that transaction that includes only the services through which it progresses. The visibility enables transparent asset performance observation and management. To simplify these efforts, you can also export trace data to Open Telemetry or Splunk using the *Telemetry Exporter* feature. 

//insert link to data exporter eventually

The Traces feature is available only for organizations that have the Anypoint Integration Advanced package or a Titanium subscription to Anypoint Platform.

== Before You Begin

Before you can use traces, ensure that you have:

* The Anypoint Integration Advanced package or a Titanium subscription to Anypoint Platform // replace with partial
* Mule Runtime version 4.6 or later
* Permission to view apps and APIs in Anypoint Monitoring

//Sara - I would consider making this access topic a link in all the subsequent topics. I don't want to mess up anything you have going on here, so I won't change it but I think it would be nice!
== Access Traces

include::partial$include-nav-steps-no-permissions.adoc[]

include::partial$include-nav-distributed-tracing.adoc[]

== Search for Traces

You can search for traces shown in the *Traces* overview page using a time period selector and queries. 

=== Search for Traces Using the Time Period Selector

Use the time period selector to display traces for the last given period of time (such as the last 5 or 30 minutes) or over a given date and time range. Use the drop-down in the calendar icon to select the time period to display in a graph. Your setting applies across all traces in the *Traces* overview page, including the *Trace Volume* chart. 

Anypoint Monitoring retains up 30 days of trace data.

=== Search for Traces Using Queries

Use the search bar to select fields to query entities and their traces. You can query using the following criteria:

* `business_group_id`: The ID of the business group that contains entities for which you want to see traces. This query appears in the search bar by default.
* `environment_id`: The ID of the environment that contains entities for which you want to see traces. This query appears in the search bar by default.
* `business_group_name`: The name of the business group that contains entities for which you want to see traces. 
* `entry_api_version`: The version number of the API for which you want to see traces.
* `entry_entity_id`: The ID of the entity for which you want to see traces.
* `entry_entity_name`: The name of the entity for which you want to see traces.
* `entry_entity_type`: The type of entity for which you want to see traces. You can query apps or APIs.
* `entry_span_id`: The ID of a span contained in traces.
* `entry_span_name`: The name of a span contained in traces.
* `environment_name`: The name of the environment that contains entities for which you want to see traces.
* `http_status_code`: The HTTP status code associated with a trace. You can query 0, 200, or 500 codes.
* `trace_id`: The ID associated with a trace.


If no traces appear after applying a query, limit your conditions. 

== Trace Overview Metrics

The *Traces* overview page shows the *Trace Volume* chart by default, which displays both the total number of traces in Anypoint Platform and the total number of traces that have errors associated with them. You can use the time period selector to select the span of time covered by the *Trace Volume* chart. From the *Trace Volume* chart, you can click the *Trace ID* of a specific trace to view more information on the xref:trace-details.adoc[*Trace Details*] page. 
