= Viewing Traces
:page-notice-banner-message: Open Beta Release: Traces is in open beta. Any use of Anypoint Monitoring features in the beta state is subject to the applicable beta services terms and conditions.
:page-info-pills: anypoint-pricing-titanium

Track the end-to-end flow of requests through service pipelines. View traces in Open Telementry (OTEL) spans to troubleshoot requests that have errors or slow response times, optimize your resource allocation, and track requests end-to-end. For example, find and view the course of a specific transaction through the services it travels to monitor its performance. 

As an alternative to Traces, use xref:telemetry-exporter.adoc[Telemetry Exporter] with third-party observability and analytics platforms.

== Before You Begin

Before you use traces, ensure that you have:

include::reuse::partial$billing/pricing.adoc[tag=prereqBulletTitanium]

* xref:access-management::permissions-by-product.adoc#monitoring[Permission to view] Mule apps, APIs, and instances of agents, brokers, and MCP servers in Anypoint Monitoring 
* Mule runtime version 4.6 or later
* HTTP Connector version 1.8 or later
* Enabled tracing on apps deployed to CloudHub 2.0:
** xref:cloudhub-2::ch2-deploy-shared-space.adoc#enable-trace-data-collection[Enabled trace data collection for your app in a shared space]
** xref:cloudhub-2::ch2-deploy-private-space.adoc#enable-trace-data-collection[Enabled trace data collection for your app in a private space]
* Enabled trace data collection on apps that are deployed to xref:runtime-fabric::use-anypoint-monitoring.adoc#enable-trace-data[Runtime Fabric]

== Supported Runtime Plane Hosts

Traces in Anypoint Monitoring supports these runtime plane hosts:

* CloudHub 2
* Runtime Fabric

[NOTE]
Trace data collection isn't supported on apps deployed to CloudHub 1.0 or hybrid standalone deployments.

== Sampling Rate for Traces

Trace data sampling rate:

* 100%: Agents, brokers, and MCP servers
* 10%: Mule apps and APIs

== Access Traces

include::partial$include-nav-steps-no-permissions.adoc[]

include::partial$include-nav-distributed-tracing.adoc[]

== Trace Overview Metrics

Search for traces shown in the *Traces* overview page by using a time period selector and queries. 

=== Search for Traces by Using the Time Period Selector

Use the time period selector to display traces for the last given period of time (such as the last 5 or 30 minutes) or over a given date and time range. Use the drop-down in the calendar icon to select the time period to display in a graph. Your setting applies across all traces in the *Traces* overview page.

[NOTE]
Anypoint Monitoring retains up to 7 days of trace data.

=== Search for Traces Using Queries

Use the search bar to select fields to query entities and their traces. If you are at the root organization level, you can query all content across the organization. If you are in a specific business group, the query returns only content from that business group.

You can query using the following criteria:

|===
|Criterion |Description
| `api_version` | Version number of the API you want to see traces for. 
| `entity` | ID of the entity you want to see traces for.
| `entity_type` | Type of entity to see traces for. You can query apps or APIs.
| `entry_span_id` | ID of a span contained in traces.
|`entry_span_name` | Name of a span contained in traces.
| `http_status_code`| HTTP status code associated with a trace. You can query 0, 200, or 500 codes.
|`trace_id` | ID associated with a trace.
|===

If no traces appear after applying a query, limit your conditions. 

== Get Trace Details

Each trace available in the *Traces* overview page contains associated metrics for you to examine. Clicking a trace opens a *Trace Details* page, which shows the origin of the initial request, associated entities, events associated with the request, and more. Additionally, you can see flows, logs, and events associated with the trace in the form of _spans_. Each span contains details that explain the operations in the specific *Trace Detail* page.

=== Access Trace Details

include::partial$include-nav-steps-no-permissions.adoc[]

include::partial$include-nav-distributed-tracing.adoc[]

. If needed, use the search function to query the list of traces that appears in the *Traces* overview page.
. Click the trace ID of the trace you want to examine.

=== Understand Trace Details

Each trace detail page contains response times for spans at a glance. They also show the following contextual data:

* *Status Code*: The HTTP response status of the trace: 
** `0 No Response`
** `200 OK`
** `500 Internal Server Error`
* *Trace Start Time*: The time the trace initiated in UTC.
* *Total Response Time*: The time taken for the trace to execute. 
* *Root Span*: The request or operation that initiated the trace.

Within each trace detail page, the following span types are captured and displayed alongside response time (where applicable):

Flows:: Mule Flows for the selected task of the specific service.
Logs:: Contextual logs for the selected task.
Events:: Mule runtime events or user actions for the selected service.

=== View Span Details

On the *Trace Details* page, click a flow, log, or event name to expand the span and see the *Span Details* box.

The *Span Details* box contains the following information:

* *Span Name*: Name of the span.
* *Span Status*: Status of the span. 
** `OK`
** `ERROR`
* *Span ID*: ID of the span.
* *Span Kind*: Source of the span operation or request.
** `Server`
** `Internal`
** `Client`
* *Span Duration*: Time the span took to execute.
* *Span Start Time*: Time when the span started, in UTC.
* *Entity Type*: Type of entity associated with the trace. 
** `App`
** `API`
* *Entity Name*: The name of the entity associated with the trace.
* *Trace ID*: The ID of the trace in which the span occurred.
* *Parent Span ID*: ID of a span that contains the selected span. Parent spans don't have a value in this field and should be tracked by using the trace ID.
* *HTTP Status Code*: The HTTP status code of a span that is a request. Statuses include:
** `0 No Response`
** `200 OK`
** `500 Internal Server Error`

== See Also
* xref:telemetry-exporter.adoc[]
* xref:cloudhub-2::ch2-deploy-shared-space.adoc#enable-trace-data-collection[Enabled trace data collection for your app in a shared space]
* xref:cloudhub-2::ch2-deploy-private-space.adoc#enable-trace-data-collection[Enabled trace data collection for your app in a private space]