//TODO_TODO_TODO: OTHER Questions
* if/how this differs from support for RTM? 
    * forward proxy? similar to "adds support to the Runtime Manager agent for a forward proxy that is deployed in your environment"
    * background info needed to understand how this fits into a bigger picture: "intercepting and inspecting all HTTPS traffic" (what does this mean exactly?) 
* prereqs similar (see RTM doc) -- do any of the tasks and prereqs in https://beta.docs.mulesoft.com/beta-traffic-inspection/runtime-manager/rtm-traffic-inspection apply also to Monitoring 
    * Build an HTTP proxy with support for TLS connections?
    * Provision this inspection proxy to send a customer-private certificate to ... agent? 



//
//tag::traffic-inspection-overview[]
Enable traffic inspection for Anypoint Monitoring to get deeper insights into the performance and business metrics on your hybrid deployments. Intercept and inspect HTTPS traffic from on-prem Mule instances so you can discover and resolve operations and business issues proactively. 

The traffic inspection feature for standalone Mule instances adds support to the Runtime Manager agent for a forward proxy that is deployed in your environment. This proxy acts as a man-in-the-middle between Mule and the control plane, intercepting and inspecting all HTTPS traffic.

To enable traffic inspection, you must install the Mule instance and the Runtime Manager agent from scratch using the following instructions.



To enable traffic inspection, you must configure Anypoint Monitoring for on-premise environments. 
//end::traffic-inspection-overview[]
//
//
//tag::traffic-inspection-limitations[]
//TODO_TODO_TODO: QUESTION: is there a URL for the AM ZIP
* Linux only: Anypoint Monitoring agent (AM) zip provided above is limited to Linux
* Otel is not supported: Do not install the Anypoint Monitoring agent on a server that is running an Otel Collector instance.
//end::traffic-inspection-limitations[]
//
//
//
//tag::traffic-inspection-prereqs[]
//TODO_TODO_TODO: VERIFY REQS! Any others? 
* You must have a server, server group, or cluster on Runtime Manager.
* The Runtime Manager Agent must be installed. See xref:runtime-manager::runtime-manager-agent.adoc[]. 
// Perhaps if server is set up, it would be installed? Without it, I got this error: 
// NoSuchFileException: /Users/sduke/Downloads/mule-enterprise-standalone-4.8.0/conf/mule-agent.yml
//end::traffic-inspection-prereqs[]
//


//
//
//tag::traffic-inspection-procedure[]

//TODO_TODO_TODO: steps for uninstall? Who can help with that?
. If an Anypoint Monitoring agent is installed on your server, uninstall the agent.
//TODO_TODO_TODO: need URL for agent download.
. Download the Anypoint Monitoring agent zip file (`am._version_.zip`) to your Mule home directory.
. Extract the zip file to add the `am/` folder in your Mule home directory. 
. Using the command line:
.. Navigate to the `am/` folder, for example:
+
----
cd am/
----
.. Install the agent to your Linux server:
+
----
./bin/install -p http:/proxy-server:port
----
. Restart your server, server group, or cluster in Runtime Manager.
+

. Return to your `am/` folder and run the setup script:
+
----
./bin/setup
----
. After approximately five minutes, check Anypoint Monitoring for your metrics. 
//end::traffic-inspection-procedure[]
//

//
//tag::NOT-USED-YET[]
. Open the *Hybrid* settings page in Anypoint Monitoring (https://anypoint.mulesoft.com/monitoring/#/settings/hybrid[US], https://eu1.anypoint.mulesoft.com/monitoring/#/settings/hybrid[EU]). 
+
For more guidance, see xref:monitoring::monitoring-settings-page.adoc[].
//end::NOT-USED-YET[]
//