=== Create an Alert for a Chart in a Custom Dashboard

[[alerts]]

. Navigate to the configuration screen for a graph in a custom dashboard. For guidance, see xref:dashboard-custom-config.adoc[Configuring Custom Dashboards].
. Provide a general configuration for the graph that (at minimum) defines the metric, environment, and resource for which you want to set the alert. 
+
For guidance, see xref:dashboard-custom-config-graph.adoc#general_settings[General Settings].
. Navigate to the *Alert* configuration tab for the graph.
. Ensure that *Advanced Mode* is disabled.
+
Alerts aren't available for charts with advanced mode configurations. 
. Click *Add Alert*.
. Use *Alert Config* to configure the alert. See <<alert_config, Alert Config>>.
. Configure email notifications when an alert is triggered. See <<notifications, Notifications>>.
. Click *Save Changes*.
. Click `X` to exit the configuration and return to the dashboard.

Note that you can also view <<state_history, state history>> and <<delete_alert, delete>> alerts.

[[configure]]
=== Configure an Alert for a Chart in a Custom Dashboard

In the *Alert Config* section, configure the condition under which an alert is triggered.

[%header,cols="1,4"]
|===
2+| Settings for Alerts in Custom Dashboards
| Name | A title for your alert
| Severity level | The severity level of your alert.
| `Condition` | WHEN: For triggering an  alert when the metric being measured is above a specified level
|===

Available severity levels:

include::partial$include-alert-severity.adoc[leveloffset=+1]

[[notifications]]
=== Send Notifications

Configure an email notification when an alert is triggered.

[%header,cols="1,4"]
|===
2+| Notification Settings for Alerts
| `Send To` | Email address for each recipient of the alert notification. If you add or change the email address of an alert recipient, they don't receive an email until the alert is triggered.
| `Message` | Message to send to the recipient.
|===

[[state_history]]
=== Get State History

View the last fifty state changes in this section of the UI.

You can also clear the history.

[[delete_alert]]
=== Delete an Alert

To delete an alert from a chart in a custom dashboard, click *Delete* from the chart's *Alerts* tab, and  confirm your deletion.
