

//
//tag::traffic-inspection-overview[]
Intercept and inspect all HTTPS traffic through a proxy server that resides between your on-premises Mule apps and Anypoint Monitoring. To enable traffic inspection for your xref:runtime-manager::deployment-strategies.adoc#hybrid-deployments[hybrid deployments], you must install the latest Anypoint Monitoring agent.
//end::traffic-inspection-overview[]
//
//
//tag::traffic-inspection-limitations[]

At this time, the Anypoint Monitoring agent that supports traffic inspection is available for Mule instances running on _Linux_. 
//end::traffic-inspection-limitations[]
//
//
//
//tag::traffic-inspection-prereqs[]

** A Mule server that is registered in Runtime Manager is required. 
+
To set up a Mule server, see xref:runtime-manager::servers-create.adoc[].

** You must have access to Anypoint Monitoring. 
+
An Anypoint Platform administrator can provide access from Access Manager, in Anypoint Platform. For more information, see xref:monitoring::am-permissions.adoc[].

//** The Runtime Manager Agent must be installed. See xref:runtime-manager::runtime-manager-agent.adoc[].
// Perhaps if server is set up, it would be installed? Without it, I got this error: 
// NoSuchFileException: /Users/sduke/Downloads/mule-enterprise-standalone-4.8.0/conf/mule-agent.yml
//end::traffic-inspection-prereqs[]
//


//
//
//tag::traffic-inspection-procedure[]

To enable traffic inspection: 

. If an Anypoint Monitoring agent is installed on your server, uninstall the agent and delete its `/am` subfolder:

.. From your Mule home directory (`MULE_HOME`), run the following command to uninstall the agent:
+
----
./bin/uninstall 
----
.. Delete the `/am` subfolder from your Mule home directory.
//TODO_TODO_TODO: need URL for agent download.
. Download the Anypoint Monitoring agent zip file (`am._version_.zip`) to your Mule home directory.
+
The agent is available from TODO_TODO_TODO.
. Extract the zip file to add the `/am` subfolder to your Mule home directory. 
. From the command line:
.. Navigate to the `/am` subfolder, for example:
+
----
cd am
----
.. Install the agent to your Linux server:
+
----
./bin/install -p http:/proxy-server:port
----
+
Replace `+http:/proxy-server:port+` with the URI of your proxy server and port.
. Restart your server in Runtime Manager.
+
For guidance, see xref:runtime-manager::servers-actions.adoc[]
. Return to your `/am` subfolder and run the setup script:
+
----
./bin/setup
----
. After approximately five minutes, check for your server's metrics in Anypoint Monitoring. 
//end::traffic-inspection-procedure[]
//

//
//tag::NOT-USED-YET[]
. Open the *Hybrid* settings page in Anypoint Monitoring (https://anypoint.mulesoft.com/monitoring/#/settings/hybrid[US], https://eu1.anypoint.mulesoft.com/monitoring/#/settings/hybrid[EU]). 
+
For more guidance, see xref:monitoring::monitoring-settings-page.adoc[].
//end::NOT-USED-YET[]
//