= How Anypoint Monitoring Collects Metrics

The Anypoint Monitoring agent collects and aggregates metrics on a per-minute basis, so one minute is the shortest possible time increment you can examine in dashboards for your deployments. Metrics collection begins at a random second of that minute, and collection repeats at the same second in subsequent minutes. For example, if the agent collects metrics at 12:00:15, it collects them again at 12:01:15, 12:02:15, and so on.

Within a Mule app, metrics for calls made to and from a connector start on different seconds. For example, metrics for inbound calls to port 8080 might be collected at 12:00:45, 12:01:45, and 12:02:45, while metrics for outbound calls made to an endpoint might be collected at 12:00:23, 12:01:23, and 12:02:23.
Because inbound call metrics collection occurs at different seconds during a minute than call metrics for outbound calls, the total number of inbound and outbound calls reported during any minute might vary. For example, if app A reports ten outbound calls made at 12:05, app B might report that the total number of corresponding inbound calls is split between 12:04 and 12:05, or 12:05 and 12:06 time windows (namely, 12:04 reports four calls and 12:05 reports six calls, totaling the ten calls). 
